# compiler = TurboC
# compiler = BorlandC
# compiler = WatcomC

# TurboC makefile macros (?)
.IF $(compiler) == TurboC
INCLUDE = C:/TC/INCLUDE
ARFLAGS = -r
AR = ar $(ARFLAGS)
CFLAGS = -A -N -mh -I. -I../h
CC = tcc -c $(CFLAGS)
LDFLAGS = $(CFLAGS)
LD = tcc $(LDFLAGS)
LINTOPT = -iC:/lint co-tc.lnt -iC:/lint -i../h -i$(INCLUDE) options.lnt
.END

# Borland C makefile macros (?)
.IF $(compiler) == BorlandC
INCLUDE = E:/BC4/INCLUDE
ARFLAGS = -r
AR = ar $(ARFLAGS)
CFLAGS = -A -mh -I. -I../h
CC = bcc -c $(CFLAGS)
LDFLAGS = $(CFLAGS)
LD = bcc $(LDFLAGS)
LINTOPT = -iC:/lint co-bc.lnt -iC:/lint -i../h -i$(INCLUDE) options.lnt
.END

# makefile for WATCOM macros
.IF $(compiler) == WatcomC
INCLUDE = C:/WATCOM/H
ARFLAGS = -r
AR = ar $(ARFLAGS)
CFLAGS = /fpi87 /sg /i="c:\watcom\h"
CC = wcc386 $(CFLAGS)
LDFLAGS = $(CFLAGS) /k8192 /l=dos4g
LD = wcl386 $(LDFLAGS)
LINTOPT = -iC:/lint co-wc.lnt -iC:/lint -i../h -i$(INCLUDE) options.lnt
.END

%.obj : %.c
	$(CC) $^

header = ../h/readdata.h ../h/utility.h
subs = readdata.c
object = readdata.obj
libs = ..\\\utility\\\utility.lib

diff : result0 result
	- diff -h -b result0 result > diff
	if test -s diff ; then vi diff ; else print NO CHANGE ; fi

result .PRECIOUS : testprog.exe testdata.dat
	testprog > result

testprog.exe : testprog.obj readdata.lib $(libs)
	$(LD) testprog.obj readdata.lib $(libs)

$(object) : $(header)
readdata.lib : $(object)
	$(AR) readdata.lib $(object)

lint  : testprog.c $(header) $(subs)
	- lint $(LINTOPT) -e771 testprog.c $(subs) > lint

clean :
	rm -f *.obj *.lib *.exe *.err
